export enum COMMUNITY_MEMBER_REPORT_REASON {
  SPAM = "SPAM",
  BULLY_THREATEN_HARASS = "BULLY_THREATEN_HARASS",
  VIOLENT_PORN_SEX = "VIOLENT_PORN_SEX",
  FAKE = "FAKE",
  ILLEGAL = "ILLEGAL",
  OTHERS = "OTHERS",
}
